const OptionActionTypes = {
	SET_SCAN_MODE: 'SET_SCAN_MODE',
	SET_OUTPUT_MODE: 'SET_OUTPUT_MODE',
	SCROLL_IMAGES_CONTAINER: 'SCROLL_IMAGES_CONTAINER',
	SET_IMPORTED_IMAGE: 'SET_IMPORTED_IMAGE',
}

export default OptionActionTypes
