const ImageActionTypes = {
	ADD: 'ADD_IMAGE',
	REMOVE: 'REMOVE_IMAGE',
	MOVE_LEFT: 'MOVE_LEFT',
	MOVE_RIGHT: 'MOVE_RIGHT',
	SET_CURRENT_IMAGE_INDEX: 'SET_CURRENT_IMAGE_INDEX',
}

export default ImageActionTypes
